added address index information to SubAddress instances
python-monero/monero-python pull request #9
Opened 2019-02-25 23:38 UTC by dethos

Fixes issue #3 

This pull request fixes the issue with  `address_index` information not being stored on `SubAddress`. 
There might be other occurrences that I wasn't able to find, but at least in 2 use cases this new information was added. 

`address_index` was added as an optional parameter to avoid breaking existing code.

2019-02-26 08:15 UTC, domol requested changes
looks good except typo in doc.

2019-02-26 08:15 UTC, Domol commented on monero/address.py
> +                    "SubAddress index must be an integer bigger then 0"
than ;)

2019-02-26 10:56 UTC, dethos commented on monero/address.py
> +                    "SubAddress index must be an integer bigger then 0"
Fixed

2019-03-18 08:28 UTC, lalvarezguillen approved these changes
Looks good to me

2019-03-18 08:47 UTC, domol approved these changes

2019-03-18 10:05 UTC, merged